Formula1/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include
from formula import views
from formula.views import CustomLogoutView
from . import settings


urlpatterns = [
    path('', views.redirectView),
    path('formula/', views.index, name='index'),
    path('formula/', include('formula.urls')),
    path('accounts/logout/', CustomLogoutView.as_view(), name='logout'),
    path('accounts/login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

formula/urls.py
from django.urls import path
from formula import views
from django.contrib.auth.views import LogoutView
app_name = 'formula'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('profile/<str:username>/', views.show_profile, name='profile'),
    path('profile/<str:username>/edit/', views.edit_profile, name='edit_profile'),
    path('team/<slug:team_slug>/', views.show_team, name='team'),
    path('test/', views.testLogoutView),
    path('register/', views.register, name='register'),
    path('all_users/', views.all_users, name="all_users"),
    path('all_teams/', views.all_teams, name="all_teams"),
    path("teams_and_users/", views.teams_and_users, name="teams_and_users"),
    path('create_post/<slug:category_slug>/<slug:topic_slug>/', views.create_post, name='create_post'),
    path('create_topic/<slug:category_slug>', views.create_topic, name='create_topic'),
    path('<slug:category_slug>/', views.list_topics, name='topics'),
    path('<slug:category_slug>/<slug:topic_slug>/', views.list_posts, name='posts'),
    path('<slug:category_slug>/<slug:topic_slug>/<post_id>/', views.display_post, name='post'),
]

formula/forms.py
from django import forms

from formula.models import *
from formula.fields import *

class TopicForm(forms.ModelForm):
    name = forms.CharField(max_length=NAME_MAX_LENGTH,
                           help_text="Please enter the name of the topic.")
    description = forms.CharField(max_length=DESC_MAX_LENGTH,

                                  help_text="Briefly describe this topic.",
                                  widget=forms.Textarea)

    class Meta:
        model = Topic
        exclude = ('slug','category', 'date_added',)


class PostForm(forms.ModelForm):
    title = forms.CharField(max_length=NAME_MAX_LENGTH,
                            help_text="Please enter the post title.")
    description = forms.CharField(max_length=DESC_MAX_LENGTH,
                                  help_text="Briefly describe your post.")
    content = forms.CharField(max_length=Post.CONTENT_MAX_LENGTH,
                              help_text="Write something here.",
                              widget=forms.Textarea)
    file = MultipleFileField(required=False)

    

    class Meta:
        model = Post
        exclude = ('topic', 'date_added', 'viewership', 'author')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password', 'first_name', 'last_name','student_id','picture','bio')


class CustomUserChangeForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'bio', 'picture') 

formula/views.py
from datetime import datetime
from zipfile import ZipFile
from io import BytesIO
import random

from django.conf.global_settings import LOGIN_URL
from django.contrib.auth.views import LogoutView
from django.conf.global_settings import LOGIN_URL
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden, JsonResponse
from django.http import HttpResponse, FileResponse
from formula.forms import *
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils import timezone
from django.db.models.functions import ExtractYear
from django.urls import reverse, NoReverseMatch
from django.shortcuts import get_object_or_404
from .forms import CustomUserChangeForm

from Formula1.settings import MEDIA_ROOT

APP_NAME = 'formula'
REGISTER_NAME = 'registration'


def index(request):
    years = list(set(Category.objects.annotate(year=ExtractYear('date_added')).values_list('year', flat=True)))
    years.sort(reverse=True)

    if not request.GET.get("year", default=False):
        year = years[0] if years else datetime.now().year
    else:
        year = int(request.GET.get("year"))
        if year not in years:
            years.append(year)
            years.sort()

    categories = set(Category.objects.annotate(year=ExtractYear('date_added')).filter(year=year))

    context_dict = {
        'year': year,
        'years': years,
        'current_year_categories': categories
    }

    return render(request, 'formula/index.html', context=context_dict)


def about(request):
    context_dict = {
        'text_description': "A forum dedicated to allowing users to communicate and learn about the development, upkeep and use of race cars. For Racers, by Racers.",
        'contact_email': "formulau1@outlook.com"
    }

    return render(request, APP_NAME + '/about.html', context=context_dict)


def list_topics(request, category_slug):
    context_dict = {}

    try:
        if request.user:
            try:
                context_dict['user_is_team_lead'] = True if TeamLead.objects.get(user=request.user) else None
            except TeamLead.DoesNotExist:
                pass
        category = Category.objects.get(slug=category_slug)
        topics = Topic.objects.filter(category=category)
        context_dict['category'] = category
        context_dict['topics'] = {topic: Post.objects.filter(topic=topic) for topic in
                                  topics}  # [{'post' : post, 'pfp' : post.author.picture} for post in list(sorted(Post.objects.filter(topic=topic), key = lambda post : post.viewership))[:3]] for topic in topics }
        return render(request, APP_NAME + '/category.html', context=context_dict)

    except Category.DoesNotExist:
        return render(request, APP_NAME + '/category.html', context={}, status=404)


def list_posts(request, category_slug, topic_slug):
    context_dict = {}

    try:
        topic = Topic.objects.get(slug=topic_slug)
        category = topic.category
        context_dict['category'] = category
        context_dict['topic'] = topic
        posts = Post.objects.filter(topic=topic)
        context_dict['topics'] = {
            topic: posts
        }

        return render(request, APP_NAME + '/topic.html', context=context_dict)

    except Topic.DoesNotExist:
        return render(request, APP_NAME + '/topic.html', context={}, status=404)


def display_post(request, category_slug, topic_slug, post_id):
    if request.GET.get('file', default=False):
        if Post.objects.get(id=post_id).file:
            zip_path = Post.objects.get(id=post_id).file.path
            zipfile = ZipFile(zip_path, 'r')
            file_bytes = zipfile.read(request.GET.get('file'))
            return FileResponse(BytesIO(file_bytes), as_attachment=True, filename=request.GET.get('file'))
    context_dict = {}
    try:
        post = Post.objects.get(id=post_id)
        context_dict['post'] = post
        context_dict['topic'] = post.topic
        context_dict['category'] = post.topic.category
        context_dict['images'] = []
        context_dict['files'] = []

        if post.file:
            zipfile = ZipFile(post.file.path, 'r')
            for filename in zipfile.namelist():
                if filename.split('.')[-1].lower() in {'apng', 'cur', 'gif', 'ico', 'jfif', 'jpeg', 'jpg', 'pjp',
                                                       'pjpeg', 'png', 'svg'}:
                    context_dict['images'].append(filename)
                else:
                    context_dict['files'].append(filename)

        return render(request, APP_NAME + '/post.html', context=context_dict)

    except Post.DoesNotExist:
        return render(request, APP_NAME + '/404.html', context={}, status=404)


def query_result(request, title_query):
    context_dict = {}

    posts = Post.objects.filter(title__contains=title_query)
    context_dict['posts'] = posts
    return render(request, APP_NAME + '/post.html', context=context_dict)


@login_required(login_url=LOGIN_URL)
def create_post(request, category_slug, topic_slug):
    try:
        topic = Topic.objects.get(slug=topic_slug)
    except Topic.DoesNotExist:
        return redirect(APP_NAME + ':index')
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if not request.user.is_superuser:
            form.fields.pop('user', None)
        if form.is_valid():
            if topic:
                post = form.save(commit=False)
                post.topic = topic
                if not request.user.is_superuser:
                    post.user = CustomUser.objects.get(username=request.user.get_name())
                post.date_added = timezone.now()
                if 'file' in request.FILES:

                    # Should allow for 99,636,535,482,328,266,092,631,578,144,895,845,295,049,065,188,420,485,120
                    # unique filenames (or 99 septendecillion 636 sexdecillion 535 quindecillion 482 quattuordecillion
                    # 328 tredecillion 266 duodecillion 92 undecillion 631 decillion 578 nonillion 144 octillion
                    # 895 septillion 845 sextillion 295 quintillion 49 quadrillion 65 trillion 188 billion
                    # 420 million 485 thousand one hundred and twenty)

                    filename_chars = "qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM_-0123456789"

                    while True:
                        filename = "".join(
                            random.choice(filename_chars) for i in range(random.randint(16, 32))) + ".zip"
                        try:
                            zipfile = ZipFile(MEDIA_ROOT + "\\post_files\\" + filename, mode='x')
                        except FileExistsError:
                            continue
                        else:
                            break

                    for file in request.FILES.getlist('file'):
                        zipfile.writestr(file.name, file.read())

                    post.file.name = "post_files\\" + filename
                    zipfile.close()
                post.save()

                return redirect(reverse(APP_NAME + ':post',
                                        kwargs={'category_slug': category_slug, 'topic_slug': topic_slug,
                                                'post_id': post.id}))

        else:
            print(form.errors)
    if not request.user.is_superuser:
        form.fields.pop('user', None)
    context_dict = {'form': form, 'topic': topic, 'category': topic.category}
    return render(request, APP_NAME + '/create-post.html', context=context_dict)


@login_required(login_url=LOGIN_URL)
def create_topic(request, category_slug):
    try:
        category = Category.objects.get(slug=category_slug)
    except Category.DoesNotExist:
        category = None
    if category is None:
        return redirect(APP_NAME + ':index')
    if not request.user.is_superuser:
        try:
            team_lead = TeamLead.objects.get(user=request.user)
            if not team_lead.topic_access.filter(category=category).exists():
                return HttpResponseForbidden("You do not have access to this category.")
        except TeamLead.DoesNotExist:
            return HttpResponseForbidden("Access denied.")
    form = TopicForm()
    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            if category:
                topic = form.save(commit=False)
                topic.category = category
                topic.date_added = timezone.now()
                topic.save()

                return redirect(reverse(APP_NAME + ':posts',
                                        kwargs={'category_slug': category_slug, 'topic_slug': topic.slug}))
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, APP_NAME + '/create-topic.html', context=context_dict)


@login_required(login_url=LOGIN_URL)
def show_profile(request, username):
    context_dict = {}
    context_dict["show_edit"] = True
    if request.user.username != username:
        context_dict["show_edit"] = False
    try:
        user = CustomUser.objects.get(username=username)
        context_dict['user'] = user
    except CustomUser.DoesNotExist:
        context_dict['user'] = None

    return render(request, APP_NAME + '/profile.html', context=context_dict)


@login_required
def edit_profile(request, username):
    context_dict = {}
    if request.user.username != username:
        return redirect(request.META.get('HTTP_REFERER', '/'))
    user = get_object_or_404(CustomUser, username=username)
    context_dict['user'] = user
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            user = form.save()
            if 'picture' in request.FILES:
                user.picture = request.FILES['picture']
            user.save()

templates/formula/about.html
{% extends 'formula/base.html' %}
{% load static %}

{% block title %}
    About FormulaU
{% endblock %}

{% block content %}
<div class="about-container" style="color: white;">
    <h1>About FormulaU Racing Team</h1>
    <p>
        {{ text_description }}
    </p>
    <p id="mail">Contact us: <a href="mailto:{{ contact_email }}" style="color: white;">{{ contact_email }}</a></p>
</div>
{% endblock %}

templates/formula/category.html
{% if category %}
	{% include 'formula/nested.html' with title=category.name description=category.description view_topic_page=True %}
{% else %}
	{% include 'formula/404.html' %}
{% endif %}

templates/formula/create-post.html
{% extends 'formula/base.html' %}

{% block extra_js %}
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
	<h1>Create a post</h1>
	<div>
		<form enctype="multipart/form-data" class="login-form" method="post" action="{% url 'formula:create_post' category.slug topic.slug  %}">
			{% csrf_token %}
			{% for hidden in form.hidden_field %}
				{{ hidden }}
			{% endfor %}
			{% for field in form.visible_fields %}
				<div class="form-group">
					{{ field.errors }}
					{{ field.help_text }}<br>
					{{ field }}
				</div>
			{% endfor %}
			<input type="submit" name="submit" value="Create post" />
		</form>
	</div>
{% endblock %}

{% block footer %}
{% endblock %}

templates/formula/create-topic.html
{% extends 'formula/base.html' %}

{% block extra_js %}
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
	<h1>Create a topic</h1>
	<div>
		<form class="login-form" method="post" action="{% url 'formula:create_topic' category.slug %}">
			{% csrf_token %}
			{% for hidden in form.hidden_field %}
				{{ hidden }}
			{% endfor %}
			{% for field in form.visible_fields %}
				<div class="form-group">
					{{ field.errors }}
					{{ field.help_text }}<br>
					{{ field }}
				</div>
			{% endfor %}
			<input type="submit" name="submit" value="Create topic" />
		</form>
	</div>
{% endblock %}

{% block footer %}
{% endblock %}

templates/formula/index.html
{% extends 'formula/base.html' %}

{% load static %}

{% block extra_js %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}?version=0">
	{% include 'formula/topic-list.html' with header=True only %} <!-- Allows us to copy the css for topic-list using different html structure -->
	{% include 'formula/tab-display.html' with header=True only %}
	<script type="text/javascript" src="{% static 'js/index.js' %}?version=0"></script>
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
	<h1>Browse categories</h1>
	{% include 'formula/tab-display.html' with end=False tabs=years content_class="category" tab_selected_func="update_categories" active_tab=year only %}
		{% for category in current_year_categories %}
			<a href="{% url 'formula:topics' category.slug %}">{{ category.name }}</a>
		{% empty %}
			<div>There were no categories for this year</div>
		{% endfor %}
	{% include 'formula/tab-display.html' with end=True only %}
{% endblock %}

{% block footer %}
{% endblock %}

templates/formula/nested.html
{% extends 'formula/base.html' %}

{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block extra_js %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/nested.css' %}?version=0" />
	{% include 'formula/topic-list.html' with header=True only %}
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
	<h1>{{ title }}</h1>
		<p>{{ description }}</p>
		<hr>
		<div class="above-list">
			<a {% if topic %}href="{% url 'formula:topics' category.slug%}">View category page{% else %} href="{% url 'formula:index'%}">View all categories{% endif %}</a>
			<h3>{% if topic %}Posts under this topic{% else %}Topics under this category{% endif %}</h3>
			{% if topic %}
				<a href="{% url 'formula:create_post' category.slug topic.slug %}">Create post</a>
			{% else %}
				{% if user_is_team_lead %}
					<a href="{% url 'formula:create_topic' category.slug%}">Create topic</a>
				{% else %}
					<div></div>
				{% endif %}
			{% endif %}
		</div>
		{% for topic, posts in topics.items %}
			{% include 'formula/topic-list.html' %}
		{% empty %}
			<div class="category">
				<div>
					There are no topics under this category :(
				</div>
			</div>
		{% endfor %}
{% endblock %}

{% block footer %}
{% endblock %}

templates/formula/post.html
{% extends 'formula/base.html' %}

{% load static %}

{% block title %}{% if post %}{{ post.title }}{% else %}{{ 404 }}{% endif %}{% endblock %}

{% block extra_js %}
	{% if post %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/post.css' %}?version=0" />
	{% else %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/error.css' %}?version=0" />
	{% endif %}
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
	{% if post %}
		<h1>{{ post.title }}</h1>
		<i>by {{ post.user }}</i>
		{% for paragraph in post.content.splitlines %}
			<p>{{ paragraph }}</p>
		{% endfor %}
		{% if files or images %}
			<hr>
			<p>
				Attached file(s):
				{% for filename in files %}
					<a href="{% url 'formula:post' category.slug topic.slug post.id %}?file={{filename}}">{{ filename }}</a>{% if not forloop.last %},{% endif %}
				{% endfor %}
			</p>
			{% for filename in images %}
				<div class="imagename"><a href="{% url 'formula:post' category.slug topic.slug post.id %}?file={{ filename }}">{{ filename }}</a></div>
				<a href="{{ post.file.url }}" class="image-link">
					<img src="{% url 'formula:post' category.slug topic.slug post.id %}?file={{ filename }}" alt="Could not load file" />
				</a>
			{% endfor %}
		{% endif %}
	{% endif %}
{% endblock %}

{% block footer %}
{% endblock %}

templates/formula/tab-display.html
{% if header %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/tab-display.css' %}?version=0" />
	<script type="text/javascript" src="{% static 'js/tab-display.js' %}?version=0"></script>
{% else %}
	{% if not end %}
	<div id="tabs-display">
		<div id="tabs-bar">
			<ul>
				{% for tab in tabs %}
					<li class="tab{% if tab == active_tab %} active{% endif %}" onclick="set_active_tab({{ forloop.counter0 }}, {{ tab_selected_func }})  " data-username="{{ tab }}" data-team="{{ team.slug }}" >
						<span>{{ tab }}</span>
					</li>
				{% endfor %}
			</ul>
		</div>
		<div id="tabs-display-content" class="{{ content_class }}">
	{% else %}
		</div>
	</div>
	{% endif %}
{% endif %}

templates/formula/team.html
{% extends 'formula/base.html' %}

{% load static %}

{% block title %}{{ team.name }}{% endblock %}

{% block extra_js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/team.css' %}?version=0" />
	{% include 'formula/topic-list.html' with header=True only %}
	{% include 'formula/tab-display.html' with header=True only %}
	<script src="{% static 'js/team.js' %}?version=0"></script>
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
	<h1>{{ team.name }}</h1>
	{% for paragraph in team.description.splitlines %}
	<p id="team_description">
		{{ paragraph }}
	</p>
	{% empty %}
	<p>
		<i>Team has set no description</i>
	</p>
	{% endfor %}
	<hr>
	<h3>Meet the team!</h3>
	{% if team_members_names %}
		{% include 'formula/tab-display.html' with team=team end=False tabs=team_members_names tab_selected_func="update_profile" active_tab=selected.username only %}
			<img id="pfp" src="{{ selected.picture.url }}" alt="pfp"/>
			<div class="member_information">
				<h2>{% if selected == team_lead.user %}Team lead{% else %}Team member{% endif %}&ensp;·&ensp;{{ selected.username }}</h2>
                <h2>Full name: {{ selected.get_full_name|default:"N/A" }}</h2>
				<span>Memer since: {{ selected.date_joined|date:"d M, Y" }}</span>
                <br>
                <span>Last login: {{ selected.last_login }}</span>
                <br>
                <span>Student Id: {% if selected.student_id %}{{ selected.student_id }}{% endif %}</span>
                <br>
                <span>Email: {{ selected.email }}</span>
                <br>
				<span>Bio: {% if selected.bio %}{{ selected.bio }}{% else %}<i>User has no bio set</i>{% endif %}</span>
			</div>
		{% include 'formula/tab-display.html' with end=True only%}
	{% else %}
	<p>There are no team members.</p>
	{% endif %}
	<hr>
	<h3>Browse their topics</h3>
	<div>
		{% for topic, posts in topics.items %}
			{% include 'formula/topic-list.html' with category=topic.category %}
		{% endfor %}
	</div>
{% endblock %}
{% block footer %}
{% endblock %}

templates/formula/teams.html
{% extends 'formula/base.html' %}

{% load static %}

{% block extra_js %}
<link rel="stylesheet" type="text/css" href="{% static 'css/teams_and_people.css' %}?version=2" />
{% endblock %}

{% block content %}
<div class="heading">
    <h1>Here are all the teams we have in FormulaU.</h1>
</div>
<div class="teams-container">
    {% for team, member_count in teams_with_members %}
    <div class="team">
        <a href="{% url 'formula:team'  team.slug %}" class="team-name">{{ team.name }}</a>
        <span class="member-count">{{ member_count }} Members</span>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/formula/teams_and_people.html
{% extends 'formula/base.html' %}

{% load static %}



{% block extra_js %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/teams_and_people.css' %}?version=2" />
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="heading">
    <h1>
    Here you can visit lists of all the teams and all the users.
    </h1>
    <h5>
    Beware, you need to have an account to check personal information of teams and users.
    </h5>
    </div>
    <div class="buttons">
	<a class="button" href="{%url 'formula:all_teams' %}">Visit the Teams page</a>
    <img src="/static/images/bolt.png" class="bolt-img1" alt="Shit">
    <a class="button" href="{%url 'formula:all_users' %}">Visit the Users page</a>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

templates/formula/topic-list.html
{% load team_tags %}
{% if header %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/topic-list.css' %}?version=0" />
{% else %}
	<div class="category">
		<div>
			<span>{{ topic.name }}</span>
		</div>
		{% if view_topic_page %}
			<a href="{% url 'formula:posts' topic.category.slug topic.slug %}" class="view-topic-page">
				<span>View topic page</span>
			</a>
		{% endif %}
		{% for post in posts %}
			<div>
				<a class="post-link" href="{% url 'formula:post' category.slug topic.slug post.id %}">
					<span>{{ post.title }}</span>
					<div class="space"></div>
					<div class="post-details" style="width: 3cm;">
						{{ post.date_added|date:"d M, Y" }}
					</div>
				</a>
				<hr>
				<a class="author-link" href="{% url 'formula:profile' post.user.username%}">
					<div class="author-details">
						<img src="{{ post.user.picture.url }}" alt="pfp" class="pfp"/>
						<div id="author-name">{{ post.user.username }}</div>
					</div>
				</a>
				<hr>
                {% if post.user|is_team_member %}
                <a class="team-link" href="{% url 'formula:team' post.user|team|slugify%}">
					<div class="team-details">
							<img src="/static/images/member.png" class="pfp" alt="Team img">
							<div>{{ post.user|team }}.</div>
					</div>
                 </a>
                {% else %}
                    <span class="team-link"  >
                    <div class="team-details">
							No team
                        </div>
                    </span>
                {% endif %}
			</div>
		{% empty %}
			<div class="empty">
				<span>There are no posts under this topic :(</span>
			</div>
		{% endfor %}
	</div>
{% endif %}

templates/formula/topic.html
{% if topic %}
	{% include 'formula/nested.html' with title=topic.name description=topic.description view_topic_page=False %}
{% else %}
	{% include 'formula/404.html' %}
{% endif %}

templates/formula/users.html
{% extends 'formula/base.html' %}

{% load static %}

{% block extra_js %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/users_list.css' %}?version=1" />
{% endblock %}

{% block content %}
        <h1>
    Here you can visit list of all the users.
    </h1>
<div class="users-container">
    {% for user, team_name in users_with_teams %}
    <div class="user">
        <a class="user-link" href="{% url 'formula:profile' user.username %}">
{% if user.picture.url %}
    <img src="{{ user.picture.url }}" alt="User Profile Picture" class="pfp">
{% else %}
    <img src="{% static 'images/default-profile-image.svg' %}" alt="Default Profile Picture" class="pfp">
{% endif %}
<span>{{ user.username }}</span>

            <span>{{ user.username }}</span>
        </a>
        {% if team_name %}
        <a class="team-link" href="{% url 'formula:team' team_name|slugify %}">{{ team_name }}</a>
        {% else %}
        <span class="team-link empty">No team</span>
        {% endif %}
    </div>
    {% endfor %}
</div>
{% endblock %}